### ISSUE TITLE
ProGuard publish

### ISSUE THREAD

**Issue by IevgeniiB** [sbt/sbt-proguard#11]
Hi, guys! Have you ever tried to publish obfuscated by ProGuard jar using sbt?
I'm trying to do something like this:

```
artifact in (Compile, ProguardKeys.proguard) ~= {
  art => art.copy(`classifier` = Some("proguard"))
}
addArtifact(artifact in (Compile, ProguardKeys.proguard), ProguardKeys.proguard)
```

But seems that `ProguardKeys.proguard` has different type from which sbt wants in `addArtifact` step

**Comment by SethTisue** [comment]
what is the error message you get? what are the two types involved? is there some difficulty converting between them?

**Comment by SethTisue** [comment]
this appears to be highly relevant: https://stackoverflow.com/questions/34861298/how-can-i-publish-obfuscated-with-proguard-jar-using-sbt#45225881
