### ISSUE TITLE
Sample for play framework

### ISSUE THREAD

**Issue by vooolll** [sbt/sbt-proguard#12]
Is anybody have used proguard for play framework, when I do it I provided this config keys in build.sbt:

```
ProguardKeys.proguardVersion in Proguard := "5.2.1",

ProguardKeys.options in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings"),

ProguardKeys.merge in Proguard := true,

ProguardKeys.options in Proguard += ProguardOptions.keepMain("play.core.server.ProdServerStart"),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("META-INF/*".r),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("controllers/*".r),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("schemas/*".r),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("org/apache/commons/logging/*".r),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("mozilla/*".r),

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.append("reference.conf")
```

But I can't run it in production mode, log message:
Caused by: b.b.a.c: reference.conf @ jar:file:/usr/share/myapp/lib/myapp_2.11-1.0.0.jar!/reference.conf: 1043: Expecting end of input or a comma, got 'play' (if you intended 'play' to be part of a key or string value, try enclosing the key or value in double quotes)

**Comment by pvlugter** [comment]
Error seems to suggest missing newline between the merged `reference.conf`s? Could check whether a trailing newline in the app `reference.conf` is enough. If this is it, then the `append` strategy could be updated to ensure newlines — confirmation that it works, or pull requests welcome.

**Comment by Enalmada** [comment]
sbt-proguard looks awesome but I am stuck trying to use the result with playframework.  Can anyone provide advice on how merge the output of sbt-proguard back into the normal playframework dist zip flow?  After running sbt-proguard, I see a "target\scala-2.12\proguard" directory with some stuff in it (a merged directory, configuration.profile , and myApp_2.12-0.1.0.jar) but I am not sure what to do with it.  Thanks for your help.

**Comment by F0bi** [comment]
@vooolll Have you solved it? @Enalmada and you?

**Comment by vooolll** [comment]
@F0bi I didn't manage to integrate it with play framework unfortunately

**Comment by SethTisue** [comment]
I think this is out of scope in this repo, so I've closed the ticket, but feel free to continuing discussing, regardless
