### ISSUE TITLE
Bad temporary path generation under Windows leads to crash

### ISSUE THREAD

**Issue by p-pavel** [sbt/sbt-proguard#14]
from Merge.scala: 

```
def entries(sources: Seq[File], tmp: File): Seq[Entry] = {
    sources flatMap { source =>
     val base = if (ClasspathUtilities.isArchive(source)) {
     val unzipped = tmp / source.getCanonicalPath
     IO.unzip(source, unzipped)
     unzipped
   } else source
   (base.*** --- base).get x relativeTo(base) map { p => Entry(p._2, p._1, source) }
  }
 }
```

createing unzipped = tmp / source.getCanonicalPath does not work on windows, because canonical path will contain ':' character which is not allowed as path of directory or file name

**Comment by jdrews** [comment]
I believe #13 and #6 are all related errors. Can confirm this issue happens in Windows 10 as well.
