### ISSUE TITLE
Instructions to obfuscate a JAR produced by sbt assembly

### ISSUE THREAD

**Issue by JithinThomas** [sbt/sbt-proguard#23]
Hi,

I'm trying to obfuscate a jar file produced by `sbt assembly`. I added the following changes to build.sbt (based on the answer provided in [this](https://stackoverflow.com/questions/39655207/how-to-obfuscate-fat-scala-jar-with-proguard-and-sbt) SO post):

```
enablePlugins(SbtProguard)
ProguardKeys.inputs in Proguard := Seq(baseDirectory.value / "target" / s"scala-${scalaVersion.value.dropRight(2)}" / s"${name.value}-assembly-${version.value}.jar")
ProguardKeys.libraries in Proguard := Seq()
ProguardKeys.inputFilter in Proguard := { file => None }
ProguardKeys.merge in Proguard := false
(ProguardKeys.proguard in Proguard) <<= (ProguardKeys.proguard in Proguard).dependsOn(assembly)
```

However, when I run `'sbt assembly` with these changes, I hit the following error:

```
/home/jithinpt/Documents/apps-infra/monitor/build.sbt:13: error: not found: value inputs
inputs in Proguard := Seq(baseDirectory.value / "target" / s"scala-${scalaVersion.value.dropRight(2)}" / s"${name.value}-assembly-${version.value}.jar")
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

```

**Is there documentation that lists the steps to follow to obfuscate a jar (produced by `sbt assembly`) using `sbt-proguard`?**

Thanks,
Jithin

**Comment by pvlugter** [comment]
The plugin keys were updated in #19. They're now namespaced appropriately with "proguard" prefix. And it's now an AutoPlugin, so keys will be auto-imported into your `build.sbt`. So you can replace `ProguardKeys.inputs` with `proguardInputs` and similarly for the other keys. See this file for the key names:

https://github.com/sbt/sbt-proguard/blob/master/src/main/scala/com/typesafe/sbt/ProguardKeys.scala

There's not currently documentation for running proguard on an assembly jar. This would be a useful contribution, if you'd like to write something up.
