### ISSUE TITLE
Publish a Library with no Main Method

### ISSUE THREAD

**Issue by DanielGGordon** [sbt/sbt-proguard#25]
Currently, proguard plugin will only publish main methods. There is no way to specify library functions, or a library that simply does not have a main method. This is possible in proguard itself.

**Comment by pvlugter** [comment]
You can put any proguard config. For example:

```
proguardOptions in Proguard += """
-keep public class sample.SomeClass {
  public static java.lang.String someMethod();
}
"""
```
