### ISSUE TITLE
replace this plugin with 100 lines

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-proguard#28]
offered under Apache 2.0, and using `sbt-assembly` to do the initial jar construction.

```scala
import sbt._
import sbt.Keys._

import sbtassembly.AssemblyPlugin, AssemblyPlugin.autoImport._

object ProguardKeys {
  val proguard = taskKey[File]("builds the proguarded jar file")
  val proguardOptions = settingKey[Seq[String]]("CLI options")
  val proguardVersion = settingKey[String]("proguard's artefact version")

  val Proguard: Configuration = config("proguard").hide
}

object ProguardPlugin extends AutoPlugin {
  val autoImport = ProguardKeys
  import autoImport._

  override def requires = AssemblyPlugin
  override def trigger = noTrigger
  override def projectConfigurations = Seq(Proguard)

  override def projectSettings =
    Seq(
      proguardOptions := Nil,
      proguardVersion := "5.3.3",
      libraryDependencies += "net.sf.proguard" % "proguard-base" % proguardVersion.value % Proguard,
      proguard := {
        val app_jars = (managedClasspath in Proguard).value

        // not java 9 compatible...
        val syslib = file(scala.util.Properties.jdkHome) / "jre/lib/rt.jar"

        val options = ForkOptions(
          javaHome = javaHome.value,
          outputStrategy = outputStrategy.value,
          bootJars = Vector.empty[java.io.File],
          workingDirectory = Option(baseDirectory.value),
          runJVMOptions = (javaOptions in proguard).value.toVector,
          connectInput = connectInput.value,
          envVars = Map.empty[String, String]
        )

        FileFunction
          .cached(streams.value.cacheDirectory / "proguard") {
            (in: Set[File]) =>
              val Seq(input) = in.toSeq
              val out = target.value / s"${name.value}-proguard-${version.value}.jar"
              new ForkRun(options)
                .run(
                  "proguard.ProGuard",
                  Attributed.data(app_jars),
                  Seq("-injars", input.getCanonicalPath) ++
                    Seq("-outjars", out.getCanonicalPath) ++
                    Seq("-libraryjars", syslib.getCanonicalPath) ++
                    proguardOptions.value,
                  state.value.log
                )
                .failed
                .foreach(f => sys.error(f.getMessage))
              Set(out)
          }(Set(assembly.value))
          .head
      }
    ) ++ inConfig(Proguard)(
      managedClasspath := Classpaths
        .managedJars(configuration.value, classpathTypes.value, update.value)
    )
}
```

Although I note that scala apps do tend to still miss out on basic things like `scala.Int` so I'm pretty sure proguard has a tonne of bugs in it.

**Comment by ryan-williams** [comment]
passing comment, this is very interesting, thanks!

i've been meaning to look into how (sbt-)proguard relates to sbt-assembly / "assembly plugins" in general (e.g. sbt-{assembly,pack}, maven-assembly-plugin)

it seems like proguard has more functionality, e.g. shrinking/obfuscation of classfiles/names, dead-code removal, some higher-level rewriting capabilities (e.g. changing select things' visibility to private), etc.

part of what you've done here is delegated a bunch of functionality that sbt-assembly also does (building an assembly JAR, merging files with configurable merge-strategies) to sbt-assembly, which is perhaps an extra win bc those code paths are better-maintained over there than the "redundant" versions of them in this repo are?

thanks in advance for any clarifications anyone wants to add!

**Comment by fommil** [comment]
Yup this restricts proguard to its optimisation / obfuscation / shrinking. I think proguard is still doing too much, it would be better if they released these things as separate tools.

**Comment by ryan-williams** [comment]
cool! in your ideal world would each of those stages:

[![](https://cl.ly/0e0M1l0Q030G/Screen%20Shot%202018-01-01%20at%202.56.55%20PM.png)](https://www.guardsquare.com/en/proguard/manual/introduction)

be exposed for library use (e.g. by this plugin) instead of hidden behind the one "monolithic" CLI (that you're getting at them via here)?

are they not exposed for that kind of use today given how it's currently published?

(happy to take this to e.g. [sbt-assembly gitter](https://gitter.im/sbt/sbt-assembly) if that would be better)

**Comment by fommil** [comment]
Yeah, exactly. The optimisation step is particularly interesting in Scala because we could do all kinds of specific optimisations when we can assume pure fp code is being used.

**Comment by ryan-williams** [comment]
that's fascinating; is there more discussion of making that happen anywhere?

**Comment by fommil** [comment]
Nowhere I know of, and I don't have the time to make it happen.
