### ISSUE TITLE
OutOfMemory Error and no way to increase heap

### ISSUE THREAD

**Issue by windemut** [sbt/sbt-proguard#3]
I have a lot of jars to package, and proguard crashes on me before it finishes writing out the jar. Increasing heap for SBT does not seem to help at all, and a visit to top or ps confirms that the proguard process still tries to slug away at around 250-300M. I was happy to see a related thread on StackOverflow, with these recommendations:

javaOptions in proguard := Seq("-Xmx2G"),

or

javaOptions in proguard := Seq("-Xmx..."),

or 

inConfig(Proguard)(javaOptions in ProguardKeys.proguard := Seq("-Xmx2g")),

proposed in sequence because the ones before were not working for someone. 

Alas, none of those works for me. I see the 4G with show:

> show proguard:proguard::java-options
> [info] myproject/proguard:proguard::javaOptions
> [info]  List(-Xmx4G)
> [success] Total time: 0 s, completed Jun 10, 2014 11:01:10 PM

But the process still runs out of memory at around 300M. 

Am I missing something?
# 

Settings: 

Seq(
  options in Proguard ++= Seq("-dontwarn", "-dontoptimize", "-dontobfuscate"),
  javaOptions in (Proguard, proguard) := Seq("-Xmx4G"),
  //javaOptions in Proguard := Seq("-Xmx2G"),
  options in Proguard += "-keep class my.main.Class { *; }"
)

Stack trace:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
[error]     at proguard.classfile.io.LibraryClassReader.createConstant(LibraryClassReader.java:351)
[error]     at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:99)
[error]     at proguard.classfile.LibraryClass.accept(LibraryClass.java:301)
[error]     at proguard.io.ClassReader.read(ClassReader.java:86)
[error]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[error]     at proguard.io.JarReader.read(JarReader.java:65)
[error]     at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[error]     at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[error]     at proguard.InputReader.readInput(InputReader.java:226)
[error]     at proguard.InputReader.readInput(InputReader.java:200)
[error]     at proguard.InputReader.readInput(InputReader.java:178)
[error]     at proguard.InputReader.execute(InputReader.java:100)
[error]     at proguard.ProGuard.readInput(ProGuard.java:197)
[error]     at proguard.ProGuard.execute(ProGuard.java:79)
[error]     at proguard.ProGuard.main(ProGuard.java:484)
[error] Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
[error]     at proguard.classfile.io.LibraryClassReader.visitUtf8Constant(LibraryClassReader.java:274)
[error]     at proguard.classfile.constant.Utf8Constant.accept(Utf8Constant.java:148)
[error]     at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:100)
[error]     at proguard.classfile.LibraryClass.accept(LibraryClass.java:301)
[error]     at proguard.io.ClassReader.read(ClassReader.java:86)
[error]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[error]     at proguard.io.JarReader.read(JarReader.java:65)
[error]     at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[error]     at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[error]     at proguard.InputReader.readInput(InputReader.java:226)
[error]     at proguard.InputReader.readInput(InputReader.java:200)
[error]     at proguard.InputReader.readInput(InputReader.java:178)
[error]     at proguard.InputReader.execute(InputReader.java:100)
[error]     at proguard.ProGuard.readInput(ProGuard.java:197)
[error]     at proguard.ProGuard.execute(ProGuard.java:79)
[error]     at proguard.ProGuard.main(ProGuard.java:484)

**Comment by darkfrog26** [comment]
Is there no work-around for this?  I've been having the same problem and nothing I do seems to resolve it.

**Comment by windemut** [comment]
I've had some luck putting this in the settings:

         javaOptions in (Proguard, ProguardKeys.proguard) := Seq("-Xmx2G"),

with these imports:

        import com.typesafe.sbt.SbtProguard._
        import com.typesafe.sbt.SbtProguard.ProguardKeys.{ options => 
proguardOptions }
        import com.typesafe.sbt.SbtProguard.ProguardOptions._

Hope this helps!

**Comment by darkfrog26** [comment]
Thanks, I ended up switching to paulp's fork and it's working now.  There seems to be a problem with using ProguardKeys.merge in Proguard := true

**Comment by andrewdbate** [comment]
+1 I'm also facing this issue, and paulp's fork seems to have been deleted.

**Comment by ctataryn** [comment]
FYI, this seemed to work for me in more recent versions (i.e. after the typelevel->lightbend name change)

```
enablePlugins(SbtProguard)

import com.lightbend.sbt.SbtProguard._

javaOptions in (Proguard, proguard) := Seq("-Xmx2G")

```
