### ISSUE TITLE
Can't get JavaObject in py4j

### ISSUE THREAD

**Issue by oxpeople** [sbt/sbt-proguard#32]
After build the proguard jar,  get javaobject can't find error.

enablePlugins(SbtProguard)

proguardOptions in Proguard += "-dontoptimize"

proguardOptions in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings")

proguardOptions in Proguard += ProguardOptions.keepMain("Test")

javaOptions in (Proguard, proguard) := Seq("-Xmx4G")

**Comment by SethTisue** [comment]
closing because report is unclear
