### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by CameronJRoss** [sbt/sbt-proguard#5]
Hi there,

Trying to run proguard:proguard when running Java 8 causes it to choke on rt.jar.  I presume this is because Proguard doesn't support it until V5 which is still in beta.  Is there any workaround for this?

Thanks,
Cameron

**Comment by dwijnand** [comment]
Indeed thank you @pvlugter!

**Comment by pauldraper** [comment]
Thanks @pvlugter.

The current latest also still works.

```scala
ProguardKeys.proguardVersion in Proguard := "5.2.1"
```

**Comment by DoctorU** [comment]
Any ideas on how to install proguard as version 5 with this problem?

I'm using brew:

```
$ brew update && brew install sbt
Warning: sbt-0.13.9 already installed
$ sbt proguard
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by pvlugter** [comment]
Latest version uses Proguard 5.3 by default.
