### ISSUE TITLE
"Duplicate zip entry in xmlbeans-2.6.0.jar" causing sbt proguard:proguard to fail

### ISSUE THREAD

**Issue by lolski** [sbt/sbt-proguard#9]
On Mac OS X 10.10, sbt 0.13.6, scala 2.11.4 and Java 1.8, running `sbt proguard:proguard` will result in the following error:

    [error] Error: Can't write [<app_path>/modules/<path>/target/scala-2.11/proguard/obfuscate] (Can't read [<home_folder>/.ivy2/cache/org.apache.xmlbeans/xmlbeans/jars/xmlbeans-2.6.0.jar(;;;;;;!META-INF/MANIFEST.MF)] (Duplicate zip entry [xmlbeans-2.6.0.jar:org/apache/xmlbeans/xml/stream/Location.class]))
    java.lang.RuntimeException: Proguard failed with exit code [1]

It seems there is a few duplicate entries in `xmlbeans-2.6.0.jar` file which I have to manually remove in order for it to work.
Here a few examples of the offending files:

    org/apache/xmlbeans/xml/stream/Location.class
    org/apache/xmlbeans/xml/stream/ProcessingInstruction.class
    org/apache/xmlbeans/xml/stream/XMLEvent.class

**Comment by pvlugter** [comment]
The readme describes how to merge the inputs to resolve duplicates:

https://github.com/sbt/sbt-proguard#merging
